languageCode = "ca-es"
title = "Arquitectura CTTI. Generalitat de Catalunya"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = true
baseURL = "https://canigo.ctti.gencat.cat"
canonifyURLs = false
disqusShortname = "arquitectura-ctti"
pluralizelisttitles = false
disablePathToLower = true

Paginate = 10


[params]
	noticieshome = 10
	destacatshome = 4
	google_analytics_id = "UA-59408075-1"
	titol = "Centre de Telecomunicacions i Tecnologies de la Informació"
	subtitol = "Arquitectura CTTI"
	blog_section = "blog"

[taxonomies]
	blog_tag = "blog_tags"
	section = "sections"

#----------------
# MENU PRINCIPAL
#----------------

[[menu.main]]
	Name = "Inici"
    Weight = 1
    Identifier = "inici"
    URL = "/"

[[menu.main]]
	Name = "Principis d'arquitectura"
    Weight = 3
    Identifier = "principis"
    URL = "/principis"   

[[menu.main]]
	Name = "Blog"
    Weight = 5
    Identifier = "blog"
    URL = "/blog"   

[[menu.main]]
	Name = "Cloud"
    Weight = 7
    Identifier = "cloud"
    URL = "/cloud"

[[menu.main]]
	Name = "Canigó"
    Weight = 9
    Identifier = "framework"
    URL = "/canigo"

[[menu.main]]
	Name = "SIC"
    Weight = 11
    Identifier = "sic"
    URL = "/sic"

[[menu.main]]
	Name = "SGDE"
    Weight = 13
    Identifier = "sgde"
    URL = "/sgde"

[[menu.main]]
	Name = "GICAR"
    Weight = 15
    Identifier = "gicar"
    URL = "/gicar"

[[menu.main]]
	Name = "Centres de Suport"
    Weight = 17
    Identifier = "suport"
    URL = "/cs"
