languageCode = "ca-es"
title = "Arquitectura CTTI. Generalitat de Catalunya"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = true
baseURL = "https://canigo.ctti.gencat.cat"
canonifyURLs = false
disqusShortname = "arquitectura-ctti"
pluralizelisttitles = false
disablePathToLower = true

Paginate = 10


[params]
	noticieshome = 10
	destacatshome = 4
	google_analytics_id = "UA-59408075-1"
	titol = "Centre de Telecomunicacions i Tecnologies de la Informació"
	subtitol = "Arquitectura CTTI"
	blog_section = "blog"

[taxonomies]
	blog_tag = "blog_tags"
	section = "sections"

#----------------
# MENU PRINCIPAL
#----------------

[[menu.main]]
	Name = "Inici"
    Weight = 1
    Identifier = "inici"
    URL = "/"

[[menu.main]]
	Name = "Arquitectura CTTI"
    Weight = 3
    Identifier = "arqctti"
    URL = "/arqctti"

[[menu.main]]
	Name = "Blog"
    Weight = 5
    Identifier = "blog"
    URL = "/blog"

[[menu.main]]
	Name = "Cloud"
    Weight = 7
    Identifier = "cloud"
    URL = "/cloud"

[[menu.main]]
	Name = "Canigó"
    Weight = 9
    Identifier = "framework"
    URL = "/canigo-fwk-docs"

[[menu.main]]
	Name = "SIC"
    Weight = 11
    Identifier = "sic"
    URL = "/sic"

[[menu.main]]
	Name = "SGDE"
    Weight = 13
    Identifier = "sgde"
    URL = "/sgde"

[[menu.main]]
	Name = "GICAR"
    Weight = 15
    Identifier = "gicar"
    URL = "/gicar"

[[menu.main]]
	Name = "Centres de Suport"
    Weight = 17
    Identifier = "suport"
    URL = "/cs"

[[menu.main]]
	Name = "Gestió Tècnica de Dades"
    Weight = 19
    Identifier = "dadesrefsuport"
    URL = "/dadesref"

[[menu.main]]
	Name = "EventHub"
    Weight = 21
    Identifier = "eventhub"
    URL = "/eventhub"

[[menu.main]]
	Name = "RPA"
    Weight = 21
    Identifier = "rpa"
    URL = "/rpa"
    
[[menu.main]]
	Name = "APIM"
    Weight = 23
    Identifier = "apim"
    URL = "/apim"

[[menu.main]]
	Name = "LowCode"
    Weight = 25
    Identifier = "lowcode"
    URL = "/lowcode"
