languageCode = "ca-es"
title = "Arquitectura CTTI. Generalitat de Catalunya"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = true
#baseURL = "https://canigo.ctti.gencat.cat"
canonifyURLs = false
disqusShortname = "arquitectura-ctti"
pluralizelisttitles = false
disablePathToLower = true
preserveTaxonomyNames = false

Paginate = 10

[markup.goldmark.renderer]
    unsafe= true

[params]
	noticieshome = 10
	destacatshome = 5
	google_analytics_id = "G-277LZ40QYF"
	titol = "Centre de Telecomunicacions i Tecnologies de la Informaci√≥"
	subtitol = "Arquitectura CTTI"
	blog_section = "blog"

[taxonomies]
	blog_tag = "blog_tags"
	section = "sections"

#----------------
# MENU PRINCIPAL
#----------------

[[menu.main]]
	Name = "Inici"
    Weight = 1
    Identifier = "inici"
    URL = "/"

[[menu.main]]
	Name = "Arquitectura CTTI"
    Weight = 2
    Identifier = "arquitectura"
    URL = "/arquitectura"

[[menu.main]]
	Name = "Blog"
    Weight = 3
    Identifier = "blog"
    URL = "/blog"

[[menu.main]]
	Name = "Plataformes i Frameworks"
    Weight = 4
    Identifier = "plataformes"
    URL = "/plataformes"

[[menu.main]]
	Name = "Centres de Suport"
    Weight = 5
    Identifier = "suport"
    URL = "/centres-suport"
